### ISSUE TITLE
Cluster Policy Reports are not updated when the policyreport output is enabled

### ISSUE THREAD

**Issue by ddrpgmv** [falcosecurity/falcosidekick#1098]
**Describe the bug**

I have deployed falco sidekick in my K8s cluster .Falco sidekick is working nominally (generates metrics, POST data to the UI, ...) .However when I enable the PolicyReport option, I get the following error: 

_2025/01/23 08:22:21 [ERROR] : PolicyReport - Can't Update the Cluster Policy Report falco-cluster-policy-report: resource name may not be empty_

**How to reproduce it**

Deploy falco sidekick and enable the Policy Report  option in the helm chart

```yaml
falcosidekick:
  enabled: true
  replicaCount: 2
  policyreport:
      enabled: true
      maxevents: 1000
      prunebypriority: true
      # -- minimum priority of event to use this output, order is `emergency\|alert\|critical\|error\|warning\|notice\|informational\|debug or ""`
      minimumpriority: ""
```

**Expected behaviour**

Cluster Policy Reports are generated using Falco events information

**Screenshots**

![Image](https://github.com/user-attachments/assets/8e453797-2ebc-42a9-bd15-887a250fe943)

![Image](https://github.com/user-attachments/assets/7dba5b21-62d3-4571-9342-1217a26f5a0d)

**Environment**

- Falco version: Falco version: 0.39.2. Falcosidekick version: 2.30.0.

- Cloud provider or hardware configuration: On premise K8s cluster (v1.28.10+rke2r1) 

- OS: Ubuntu 24.04.1 LTS

- Kernel: Linux 6.8.0-49-generic 

- Installation method: Kubernetes Helm (Chart version: 4.17.0)

**Additional context**
