### ISSUE TITLE
aws.region is not considered in irsa method auth

### ISSUE THREAD

**Issue by merbinr** [falcosecurity/falcosidekick#1133]
I explicitly set the region value in config.aws.region, But when checking inside the POD, the AWS_REGION and AWS_DEFAULT_REGION values are taken from the eks cluster's region, So when I have a bucket in other r

**How to reproduce it**
* Use EKS and IRSA for auth
* Set aws.region value in the chart values
* Perfom helm install
* Check the env variable inside the falcosidekick

**Expected behaviour**
* When config.aws.region explicitly provided, it should use that value in AWS_REGION env 

**Screenshots**
### Value.yml config
![Image](https://github.com/user-attachments/assets/e29ee9c2-2907-4245-b330-e4abf8c8546d)
### ENV inside the pod 
![Image](https://github.com/user-attachments/assets/821029a9-b3f0-4491-854c-1f987cac400d)

**Environment**
## Method
* EKS
## Values
```yaml
image:
  tag: 0.40.0
tty: true
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 150m
    memory: 150Mi


# Falco Sidekick configurations.
falcosidekick:
  enabled: true
  podSecurityContext:
    runAsUser: 0
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 150m
      memory: 150Mi
  config:
    debug: true
    aws:
      region: us-east-1
      rolearn: arn:aws:I am::<replace-it>:role/sec-engg-wlp-falco-eks-service-account
      useirsa: true
      s3:
        bucket: cwp-testing
        prefix: test/falco/cluster
        endpoint: s3.us-east-1.amazonaws.com
  
# Falco k8s-metacollector configurations.
collectors:
  kubernetes:
    enabled: true
    image:
      tag: 0.1
    serviceAccount:
      name: sec-engg-falco-sa
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 150m
        memory: 150Mi


falcoctl:
  artifact:
    follow:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 150Mi

```

**Comment by merbinr** [comment]
Due to the above issue, it will create errors when trying to upload alerts to an S3 bucket when eks and the s3 bucket are in different regions.


We can do a workaround to overwrite the AWS_REGION, We need to set it as config.extraEnv value as following 
```yaml
  config:
    extraEnv: 
      - name: AWS_REGION
        value: us-east-1
```
Here `us-east-1` is the region where the bucket is present
