### ISSUE TITLE
Support Kafka Rest Output

### ISSUE THREAD

**Issue by dirien** [falcosecurity/falcosidekick#262]
**Motivation**

The Kafka REST Proxy provides a RESTful interface to a Apache Kafka cluster, making it easy to produce and consume messages, view the state of the cluster, and perform administrative actions without using the native Kafka protocol or clients.

**Feature**

Having a new Output of type `kafkarest` in addition to Kafka.

```yaml
kafkarest:
  address: "" # The full URL to the topic (example "http://kafkarest:8082/topics/test")
  #version: 2 # Kafka Rest Proxy API version 2|1 (default: 2)
  # minimumpriority: "debug" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
  # mutualtls: false # if true, checkcert flag will be ignored (server cert will always be checked)
  # checkcert: true # check if ssl certificate of the output is valid (default: true)
```

The `Content-Type: application/vnd.kafka.binary.v2+json` will produce the key value pairs exactly as passed them, without adding escaped quotes to string keys.

On note, why a normal Webhook is not suitable neither, Kafka Rest Proxy expects the data on following message body:
```json
{"records":[{"value":"falcoPayload"}]}
```
**Alternatives**

Using the existing Kafka Output, but need to extend it to support cert or sasl. This is realy not the easy. I would rather let it like this and use the rest proxy as an entry. The Rest proxy user can be set specific via ACL on the topic.

**Additional context**

Here the Kafka Rest Output in action
![image](https://user-images.githubusercontent.com/38325136/128419091-8aa5972b-1271-400f-acd7-c2470a9b3156.png)

And the result in Aiven UI
![image](https://user-images.githubusercontent.com/38325136/128419201-e0c48f19-29c9-4063-a12e-eedfed9caf46.png)
