### ISSUE TITLE
Is it possible to run falco + sidekick + ui in docker-compose?

### ISSUE THREAD

**Issue by Krishnacore** [falcosecurity/falcosidekick#274]
I'm trying to get everything up via docker-compose. And every component works, but I don't see any messages from falco in the dashboard. It seems to me that the containers are not communicating with each other at all... Am I missing some additional configuration?

My docker-compose.yml
```yaml
version: '3.3'
services:
    falco:
        privileged: true
        container_name: falco
        volumes:
            - '/var/run/docker.sock:/host/var/run/docker.sock'
            - '/dev:/host/dev'
            - '/proc:/host/proc:ro'
            - '/boot:/host/boot:ro'
            - '/lib/modules:/host/lib/modules:ro'
            - '/usr:/host/usr:ro'
            - '/etc:/host/etc:ro'
        image: 'falcosecurity/falco:latest'
    falco-ui:
        container_name: falco-ui
        ports:
            - '2802:2802'
        image: 'falcosecurity/falcosidekick-ui'
    falcosidekick:
        container_name: falco-sidekick
        ports:
            - '2801:2801'
        image: falcosecurity/falcosidekick
```
