### ISSUE TITLE
Elasticsearch - header missing (400)

### ISSUE THREAD

**Issue by sausagenoods** [falcosecurity/falcosidekick#348]
**Describe the bug**
Falcosidekick fails to forward events to Elasticsearch. Falcosidekick prints out error `header missing (400)`, sometimes without the `(400)`. Falco and Falcosidekick are running on the same server outside of containers, Elasticsearch is deployed within Docker Compose on another server.

**How to reproduce it**
1. Start Elasticsearch using the [docker-compose.yaml](https://github.com/falcosecurity/falcosidekick/blob/master/docker-compose.yaml) file from this repository.
```
# docker compose up elasticsearch
````

2. Configure and start Falcosidekick. config.yaml:
```yaml
customfields: # custom fields are added to falco events
  Host: "xx-xxx-xxxx"

debug: true

elasticsearch:
  hostport: "http://my_public_ip:9200" # http://{domain or ip}:{port}, if not empty, Elasticsearch output is enabled
  index: "falco" # index (default: falco)
  type: "event"
  minimumpriority: "debug" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
  suffix: "daily" # date suffix for index rotation : daily (default), monthly, annually, none
  # mutualtls: false # if true, checkcert flag will be ignored (server cert will always be checked)
  checkcert: false # check if ssl certificate of the output is valid (default: true)
  username: "elastic" # use this username to authenticate to Elasticsearch if the username is not empty (default: "")
  password: "pass" # use this password to authenticate to Elasticsearch if the password is not empty (default: "")
```
3. Run `userdel` or `useradd` on the host to trigger alerts. That's all. Falcosidekick should now fail to send the events.

**Expected behaviour**
Falcosidekick forwarding events to Elasticsearch without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/84454107/181010939-ed1e689e-eb88-41af-8238-9dffb4b0426f.png)

**Environment**

- Falco version:
```
Falco version: 0.32.1
Libs version:  0.7.0
Plugin API:    1.0.0
Driver:
  API version:    1.0.0
  Schema version: 2.0.0
  Default driver: 2.0.0+driver
```

- System info:
```json
{
  "machine": "x86_64",
  "nodename": "xx-xxx-xxxx.domain.net",
  "release": "4.19.195",
  "sysname": "Linux",
  "version": "#3 SMP Fri Aug 27 04:58:00 EDT 2021"
}
```

- OS:
```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

- Kernel:
```
4.19.195
```

- Installation method:
Installed Falco from DEB, compiled Falcosidekick from source.

**Additional context**
Attempting to post an event using curl results in this error:
```
# curl -X POST http://elastic:pass@my_public_ip:9200/falco-2022.07.26/event -d '{"output":"10:19:29.892390134: Notice User management binary command run outside of container (user=root user_loginuid=0 command=userdel test parent=bash gparent=tmux: ggparent=systemd gggparent=\u003cNA\u003e)","priority":"Notice","rule":"User mgmt binaries","time":"2022-07-26T10:19:29.892390134Z","output_fields":{"evt.time":1658830769892390134,"host":"xx-xxx-xxxx","proc.aname[2]":"tmux:","proc.aname[3]":"systemd","proc.aname[4]":null,"proc.cmdline":"userdel test","proc.pname":"bash","user.loginuid":0,"user.name":"root"},"source":"syscall","tags":["host","mitre_persistence","users"]}'

{"error":"no handler found for uri [/falco-2022.07.26/event] and method [POST]"}
```

Other than that I'm able to access and authenticate on the Elasticsearch server from the server in which Falco and Falcosidekick are running.
