### ISSUE TITLE
Add channel/channel_id in slack properties

### ISSUE THREAD

**Issue by igoritos22** [falcosecurity/falcosidekick#365]
There may be some situations where it is necessary to pass a specific channel in the slack message post. It would be interesting to have something like this:

```yaml
  slack:
    # -- Slack Webhook URL (ex: <https://hooks.slack.com/services/XXXX/YYYY/ZZZZ>), if not `empty`, Slack output is *enabled*
    webhookurl: ""
    # -- Slack Footer
    channel: ""
    # -- Channel ID
    footer: ""
    # -- Slack icon (avatar)
    icon: ""
    # -- Slack username
    username: ""
    # -- `all` (default), `text` (only text is displayed in Slack), `fields` (only fields are displayed in Slack)
    outputformat: "all"
    # -- minimum priority of event to use this output, order is `emergency\|alert\|critical\|error\|warning\|notice\|informational\|debug or ""`
    minimumpriority: ""
    # -- a Go template to format Slack Text above Attachment, displayed in addition to the output from `slack.outputformat`. If empty, no Text is displayed before Attachment
    messageformat: ""
```
