### ISSUE TITLE
Convert duplicated output fields into json array.

### ISSUE THREAD

**Issue by fordsean** [falcosecurity/falcosidekick#400]
I am running Falco in EKS and AKS, and shipping alerts to Panther (SIEM) using fluentbit. Panther uses Snowflake as a data lake. I've ran into issue defining a schema for Falco alerts and as a result of the discussion [here](https://kubernetes.slack.com/archives/CMWH3EH32/p1677121786377379), opening this feature request.


<!--
Is your feature request related to a problem?
Please describe what the problem is clearly and concisely.
Eg., I'm always frustrated when ...
-->

Modify the output field so that the fields that are duplicated withing a given event are in json array form. Here is an example: 

```json
"output_fields": {
        "container.id": "xxxxxxxxxx",
        "container.image.repository": null,
        "evt.time": 1677012173074754373,
        "fd.name": "/proc/16/environ",
        "k8s.ns.name": "osquery",
        "k8s.pod.name": "osquery-v5qtl",
        "proc.aname[2]": "containerd-shim",
        "proc.aname[3]": "systemd",
        "proc.aname[4]": null,
        "proc.cmdline": "SchedulerRunner                                                                                                                                                                                                                                                                                                                                                                                                                      ",
        "proc.name": "SchedulerRunner",
        "proc.pid": 47664,
        "proc.pname": "osqueryd",
        "user.loginuid": -1,
        "user.name": "<NA>"
```

here we see the `proc.aname` field repeated with `[2],[3] and [4]` 
this means we would have to define the schema for all possible variations of this field and potentially other fields that produce the same output. 

here is the note from panther support team:

The issue with the proc.aname fields is that they are separate fields that would need to be declared separately in a schema with square brackets in the field names.
Scenario #1: Current broken syntax
event:

```json
{"proc.aname[2]":"containerd-shim","proc.aname[3]":"systemd","proc.aname[4]":null}
```

schema:

```yml
fields:
  - name: proc.aname[2]
    type: string
  - name: proc.aname[3]
    type: string
  - name: proc.aname[4]
    type: string
```

This won’t work because field names can’t contain square brackets. This isn’t valid JSON. Array elements can’t be organized in a log as separate fields.
Scenario #2: Square bracket replacement with allowed character
event:

```json
{"proc.aname_2_":"containerd-shim","proc.aname_3_":"systemd","proc.aname_4_":null}
```

schema:

```yml
fields:
  - name: proc.aname_2_
    type: string
  - name: proc.aname_3_
    type: string
  - name: proc.aname_4_
    type: string
```

This will work because the fields don’t contain a prohibited character anymore, and Snowflake will allow these field names in the data lake.
Scenario #3: Change proc.aname to be a true array instead of referencing individual elements
event:

```json
{"proc.aname":[null,null,"containerd-shim",:"systemd",null]}
```

schema:

```yml
fields:
  - name: proc.aname
    type: array
    element: 
      type: string
```

This will work because the one field name doesn’t contain square brackets and elements in the array can be pulled in rules with the following syntax:

```python
if event.get('proc.aname', [null,null,null,null,null])[3] == "systemd":
  return true
```

There were some additional concerns raised by the Panther team regarding potential issues with some identifier fields, but from what i understand in the docs [here](https://docs.snowflake.com/en/sql-reference/identifiers-syntax), all fields containing identifier fields in Falco alerts are in compliance with Snowflake requirements. 
Here is the original message from Panther support team:

```
While Panther can parse fields with square brackets, the problem occurs when it tries to store the data in snowflake. Snowflake has stricter [Identifier Requirements](https://docs.snowflake.com/en/sql-reference/identifiers-syntax). This means you won’t get classification failures, but there will be a silent failure in the storage step going into the data lake.
```




<!--
Describe the solution you would like.
-->

It would be great to have ANY/ALL fields that are outputted in this format:

```json
    "proc.aname[2]": "containerd-shim",
        "proc.aname[3]": "systemd",
        "proc.aname[4]": null,
```

to be converted to json arrays instead. This would simplify the process of parsing Falco alerts by third party vendors such as Panther.


<!--
Describe alternatives you have considered, if any.
A clear and concise description of any alternative solutions or features you have considered.
-->

Currently i am able to ingest Falco alerts by defining the `output_field` as a json in the schema. Here is one version of schema generated based on Falco alerts that works now: 

```yml
fields:
- name: output
  type: string
  required: true
- name: priority
  type: string
  required: true
- name: rule
  type: string
  required: true
- name: time
  type: timestamp
  timeFormats:
    - rfc3339
  required: true
- name: source
  type: string
  required: false
- name: tags
  type: array
  required: false
  element:
    name: tag
    type: string
    required: false
- name: ouput_fields
  type: json
  required: false
```

<!-- Add any other context or screenshots about the feature request here. -->

helpful links: 
- [slack thread](https://kubernetes.slack.com/archives/CMWH3EH32/p1677121786377379)
- [Panther](https://panther.com/)
- [Snowflake](https://www.snowflake.com/)
