### ISSUE TITLE
falcosidekick-ui  shows "Please send with post http method" message only

### ISSUE THREAD

**Issue by cloud-66** [falcosecurity/falcosidekick#491]
**Describe the bug**

don't see anything in falcosidekick webui

**How to reproduce it**

helm install falco -n falco  ./falco -f falco-values.yaml
kubectl run event-generator -n falco --image myprivaterepo/falcosecurity/event-generator -- run syscall --loop

```
image:
  registry: myprivaterepo
tty: true
driver:
  kind: ebpf
falcosidekick:
  enabled: true
  webui:
    enabled: true
    image: 
      registry: myprivaterepo
  image:
    registry: myprivaterepo
  ingress:
    enabled: true
    hosts:
      - host: falcosidekick-ui.falco.mydomain
        paths:
        - path: /
```

**Expected behaviour**

Expect to see falcosidekick webui with security events

**Screenshots**

![image](https://github.com/falcosecurity/falcosidekick/assets/41143306/6bc31336-992c-4d28-97b6-9edb9b982d18)

![image](https://github.com/falcosecurity/falcosidekick/assets/41143306/4b2ad6a0-6439-4b59-9284-da7e460df8dd)

**Environment**

- Falco version:
0.34.1

- System info:

- Cloud provider or hardware configuration:
baremetal
- OS:
rhel 8 like OS
- Kernel:
5.15.87-1.el7.3.x86_64
- Installation method:
helm chart

**Additional context**
