### ISSUE TITLE
Can't send smtp with outlook

### ISSUE THREAD

**Issue by sbe-arg** [falcosecurity/falcosidekick#663]
on docker been playing with plain and bearer but cannot figure this out

compose file:

```
  falcosidekick:
    image: falcosecurity/falcosidekick:latest
    ports:
      - 2801:2801
    environment:
      - SMTP_AUTHMECHANISM=oauthbearer
      - SMTP_IDENTITY=email@hotmail.com
      - SMTP_HOSTPORT=smtp-mail.outlook.com:587
      - SMTP_USER=email@hotmail.com
      - SMTP_PASSWORD=mylegacypass
      - SMTP_FROM=email@hotmail.com
      - SMTP_TO=email@gmail.com
      - SMTP_TLS=true
```

```
[ERROR] : SMTP - Send Mail failure : Client not authenticated to send mail.
```
