### ISSUE TITLE
PagerDuty EU post error

### ISSUE THREAD

**Issue by PaulPowershell** [falcosecurity/falcosidekick#673]
**Describe the bug**
Impossible to creat pagerduty event on EU.
This request is the continuation of https://github.com/falcosecurity/falcosidekick/issues/496
I have this error on falcosidekick
```
PagerDuty - Post "https://events.pagerduty.com/v2/enqueue": EOF
```
I think problem come from pagerduty_test.go that not use EU url
i should have https://events.eu.pagerduty.com/v2/enqueue

I creat a new API KEY pagerduty to test the last time

**How to reproduce it**
Set parameters for pageruty
```
      config: 
        pagerduty:
          # -- Pagerduty Routing Key, if not empty, Pagerduty output is *enabled*
          routingkey: "XXXXXXXXXXXXXXXXXXXX"
          # -- Pagerduty Region, can be 'us' or 'eu'
          region: "eu"
          # -- minimum priority of event to use this output, order is `emergency\|alert\|critical\|error\|warning\|notice\|informational\|debug or ""`
          minimumpriority: "warning"
```

**Screenshots**
![image](https://github.com/falcosecurity/falcosidekick/assets/116181531/20fe58e9-ee2d-4da0-9e70-53018802614e)

**Environment**
- Falco version: 3.5.0
