### ISSUE TITLE
Export to Elasticsearch and get header missing error

### ISSUE THREAD

**Issue by zein9** [falcosecurity/falcosidekick#705]
**Describe the bug**

Export to Elasticsearch and get header missing error

**How to reproduce it**

```yaml
root@demo-192-168-60-20:~/falco# cat falco-values.yaml
USER-SUPPLIED VALUES:
driver:
  kind: ebpf
falcosidekick:
  config:
    customfields: user:eric
    elasticsearch:
      hostport: "http://<my_domain>:9200"
      username: "<my_username>"
      password: "<my_password>"
  enabled: true
tty: true
```

**Expected behaviour**

Can not upload falco logs to Elasticsearch. There are logs about header missing in notification.

**Screenshots**

<img width="1765" alt="image" src="https://github.com/falcosecurity/falcosidekick/assets/99779929/beb6adf2-883f-4b90-987b-9e9323495696">

- Falco version: 0.36.2
- Falco Sidekick version: 2.28.0
- System info:
```
root@falco-6cv99:/# falco --support | jq .system_info
Mon Dec  4 08:04:05 2023: Falco version: 0.36.2 (x86_64)
Mon Dec  4 08:04:05 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Mon Dec  4 08:04:05 2023: Loading rules from file /etc/falco/falco_rules.yaml
{
  "machine": "x86_64",
  "nodename": "falco-6cv99",
  "release": "5.4.0-163-generic",
  "sysname": "Linux",
  "version": "#180-Ubuntu SMP Tue Sep 5 13:21:23 UTC 2023"
}
```
- Cloud provider or hardware configuration: falco in k8s.
